### ISSUE TITLE
Installing Jenkins Plugins

### ISSUE THREAD

**Issue by jmdcal** [saltstack-formulas/jenkins-formula#28] opened 2015-08-05 23:34 UTC
Here is a simple hack to install plugins, maybe someone likes it. 
It is working now, needs some settings to be installed. 
you will also need to restore /var/lib/jenkins/jenkins_settings/installedPlugins.xml and then 
you will have a bunch of things like /var/lib/jenkins/*.xml that need to be setup. 
```
{% set plugins = ("analysis-collector","analysis-core","ansicolor","ant","artifactdeployer","artifactory","batch-task","build-metrics","build-publisher","checkstyle","chucknorris","cobertura","conditional-buildstep","configurationslicing","confluence-publisher","copyartifact","credentials","cvs","dashboard-view","deploy","disk-usage","email-ext","envinject","extended-choice-parameter","external-monitor-job","extra-columns","fail-the-build-plugin","git-client","git-server","git","global-build-stats","greenballs","groovy-postbuild","groovy","htmlpublisher","javadoc","jenkinswalldisplay","jira","jobConfigHistory","jquery","ldap","log-parser","mailer","mask-passwords","maven-info","maven-plugin","multiple-scms","nested-view","nodelabelparameter","pam-auth","parameterized-trigger","pmd","promoted-builds-simple","promoted-builds","publish-over-ssh","python","run-condition","scm-api","scm-sync-configuration","scp","scriptler","sectioned-view","selenium-aes","selenium","seleniumhq","shelve-project-plugin","sidebar-link","sounds","ssh-agent","ssh-credentials","ssh-slaves","ssh","subversion","svn-tag","svnpublisher","testng-plugin","text-finder","thinBackup","token-macro","translation","view-job-filters","ws-cleanup") %}

{% for plugin in plugins %}
jenkins_install_plugin_{{plugin}}_1:
  cmd.run:
    - name : curl -k -L https://updates.jenkins-ci.org/latest/{{plugin}}.hpi -o /var/lib/jenkins/plugins/{{plugin}}.hpi
    - onlyif: 'test ! -f /var/lib/jenkins/plugins/{{plugin}}.hpi'

jenkins_install_plugin_{{plugin}}_2:
  file.managed:
    - {name: "/var/lib/jenkins/plugins/{{plugin}}.hpi"}
    - {user: 'jenkins'}
    - {group: 'jenkins'}
    - {replace : False }
    - require:
      - cmd : jenkins_install_plugin_{{plugin}}_1

jenkins_install_plugin_{{plugin}}_3:
  archive.extracted:
    - name: "/var/lib/jenkins/plugins/{{plugin}}/"
    - source: "/var/lib/jenkins/plugins/{{plugin}}.hpi"
    - archive_format: zip
    - user: jenkins
    - group: jenkins
    - onlyif: 'test ! -f /var/lib/jenkins/plugins/{{plugin}}'
    - require:
      - file : jenkins_install_plugin_{{plugin}}_2

{% endfor %}

**Comment by jmdcal** [comment] 2015-08-05 23:35
I would have used file managed for the unpacking but jenkins does not provide sha sums.

**Comment by jmdcal** [comment] 2015-08-06 14:33
The chown is based on this  https://github.com/saltstack/salt/issues/26056

**Comment by blast-hardcheese** [comment] 2015-10-10 22:55
This is a duplicate of #23, and was resolved by #31

**Comment by bersace** [comment] 2015-12-03 08:50
:up: Should you close this issue ?

**Comment by gravyboat** [comment] 2015-12-03 19:29
Done, if this needs to be opened back up feel free to do so.

**Closed** 2015-12-03 19:29 UTC
